export type IconContext = 'priority' | 'sprint' | 'project' | 'state';

export interface IconItem { icon: string; label: string; name: string }
export interface IconGroup {
  label: string;
  /** Nhóm hiển thị trong những context nào; bỏ trống = mọi context */
  contexts?: IconContext[];
  icons: IconItem[];
}

/**
 * Kho icon dùng chung toàn app (PrimeIcons — bundled, license MIT).
 * Mọi icon picker (priority, sprint, project...) đều dùng danh sách này,
 * lọc theo context — KHÔNG tự khai báo danh sách icon riêng trong component.
 */
export const ICON_GROUPS: IconGroup[] = [
  {
    label: 'Flag / Priority',
    contexts: ['priority', 'sprint'],
    icons: [
      { icon: 'pi pi-flag',           label: 'Cờ',         name: 'flag cờ ưu tiên' },
      { icon: 'pi pi-flag-fill',      label: 'Cờ đậm',     name: 'flag fill cờ đậm' },
      { icon: 'pi pi-bookmark',       label: 'Đánh dấu',   name: 'bookmark đánh dấu' },
      { icon: 'pi pi-bookmark-fill',  label: 'Đánh dấu đậm', name: 'bookmark fill đánh dấu đậm' },
      { icon: 'pi pi-star',           label: 'Sao',         name: 'star sao' },
      { icon: 'pi pi-star-fill',      label: 'Sao đậm',    name: 'star fill sao đậm' },
      { icon: 'pi pi-heart',          label: 'Tim',         name: 'heart tim yêu thích' },
      { icon: 'pi pi-heart-fill',     label: 'Tim đậm',    name: 'heart fill tim đậm yêu thích' },
      { icon: 'pi pi-thumbs-up',      label: 'Tốt',         name: 'thumbs-up đồng ý tốt' },
      { icon: 'pi pi-thumbs-up-fill', label: 'Tốt đậm',   name: 'thumbs-up fill tốt đậm' },
      { icon: 'pi pi-thumbs-down',    label: 'Không tốt',  name: 'thumbs-down không đồng ý' },
      { icon: 'pi pi-thumbs-down-fill', label: 'Không tốt đậm', name: 'thumbs-down fill không đồng ý đậm' },
      { icon: 'pi pi-crown',          label: 'Vương miện', name: 'crown vương miện top ưu tiên' },
      { icon: 'pi pi-diamond',        label: 'Kim cương',  name: 'diamond kim cương quý giá' },
    ],
  },
  {
    // pi-bolt, pi-shield giữ ở Alert/Warning để tránh duplicate với Bug/Issue
    label: 'Bug / Issue',
    icons: [
      { icon: 'pi pi-ticket',               label: 'Ticket',    name: 'ticket bug issue lỗi sự cố' },
      { icon: 'pi pi-exclamation-triangle', label: 'Cảnh báo',  name: 'exclamation triangle warning bug lỗi cảnh báo' },
      { icon: 'pi pi-exclamation-circle',   label: 'Lỗi',       name: 'exclamation circle bug lỗi issue sự cố' },
      { icon: 'pi pi-times-circle',         label: 'Thất bại',  name: 'times circle error fail thất bại lỗi' },
      { icon: 'pi pi-ban',                  label: 'Chặn',      name: 'ban block chặn regression' },
      { icon: 'pi pi-wrench',               label: 'Fix',       name: 'wrench fix patch sửa lỗi' },
      { icon: 'pi pi-minus-circle',         label: 'Nhỏ',       name: 'minus circle minor nhỏ low' },
      { icon: 'pi pi-info-circle',          label: 'Thông tin', name: 'info circle known issue thông tin' },
    ],
  },
  {
    // pi-exclamation-triangle/circle, pi-ban, pi-times-circle chuyển sang Bug/Issue
    label: 'Alert / Warning',
    contexts: ['priority'],
    icons: [
      { icon: 'pi pi-bolt',       label: 'Tia sét',  name: 'bolt tia sét khẩn cấp critical' },
      { icon: 'pi pi-shield',     label: 'Bảo vệ',   name: 'shield bảo vệ an toàn security' },
      { icon: 'pi pi-lock',       label: 'Khóa',     name: 'lock khóa bảo mật' },
      { icon: 'pi pi-unlock',     label: 'Mở khóa',  name: 'unlock mở khóa truy cập' },
      { icon: 'pi pi-eye',        label: 'Xem',      name: 'eye xem theo dõi' },
      { icon: 'pi pi-eye-slash',  label: 'Ẩn',       name: 'eye slash ẩn bí mật' },
    ],
  },
  {
    // pi-bolt chuyển sang Alert/Warning; pi-sitemap chuyển sang Project
    label: 'Sprint / Agile',
    contexts: ['sprint'],
    icons: [
      { icon: 'pi pi-sync',           label: 'Lặp',       name: 'sync vòng lặp iteration sprint' },
      { icon: 'pi pi-refresh',        label: 'Làm mới',   name: 'refresh làm mới chu kỳ cycle' },
      { icon: 'pi pi-forward',        label: 'Tiến',      name: 'forward tiến tới' },
      { icon: 'pi pi-fast-forward',   label: 'Nhanh',     name: 'fast forward nhanh tốc độ cao' },
      { icon: 'pi pi-compass',        label: 'La bàn',    name: 'compass la bàn định hướng' },
      { icon: 'pi pi-send',           label: 'Gửi',       name: 'send gửi phóng' },
      { icon: 'pi pi-bullseye',       label: 'Mục tiêu',  name: 'bullseye mục tiêu target' },
      { icon: 'pi pi-calendar',       label: 'Lịch',      name: 'calendar lịch thời gian' },
      { icon: 'pi pi-calendar-times', label: 'Hủy lịch',  name: 'calendar times hủy lịch' },
      { icon: 'pi pi-stopwatch',      label: 'Bấm giờ',   name: 'stopwatch bấm giờ timebox' },
      { icon: 'pi pi-history',        label: 'Lịch sử',   name: 'history lịch sử chu kỳ' },
      { icon: 'pi pi-gauge',          label: 'Tốc độ',    name: 'gauge velocity tốc độ' },
      { icon: 'pi pi-trophy',         label: 'Cúp',       name: 'trophy cúp thành tích goal' },
      { icon: 'pi pi-rocket',         label: 'Tên lửa',   name: 'rocket tên lửa phóng launch' },
      { icon: 'pi pi-wave-pulse',     label: 'Nhịp tim',  name: 'wave pulse nhịp tim hoạt động' },
      { icon: 'pi pi-chart-line',     label: 'Biểu đồ',   name: 'chart line biểu đồ xu hướng' },
      { icon: 'pi pi-list',           label: 'Danh sách', name: 'list danh sách backlog' },
      { icon: 'pi pi-check',          label: 'Hoàn thành', name: 'check hoàn thành done' },
    ],
  },
  {
    // pi-bookmark chuyển sang Flag/Priority; pi-shield chuyển sang Alert/Warning
    label: 'Project',
    contexts: ['project'],
    icons: [
      { icon: 'pi pi-folder',           label: 'Thư mục',   name: 'folder thư mục' },
      { icon: 'pi pi-folder-open',      label: 'Mở',        name: 'folder open thư mục mở' },
      { icon: 'pi pi-briefcase',        label: 'Cặp',       name: 'briefcase cặp công việc' },
      { icon: 'pi pi-building',         label: 'Tòa nhà',   name: 'building tòa nhà công ty' },
      { icon: 'pi pi-building-columns', label: 'Cơ quan',   name: 'building columns cơ quan tổ chức' },
      { icon: 'pi pi-box',              label: 'Hộp',       name: 'box hộp module' },
      { icon: 'pi pi-globe',            label: 'Toàn cầu',  name: 'globe toàn cầu web' },
      { icon: 'pi pi-sitemap',          label: 'Sơ đồ',     name: 'sitemap sơ đồ cấu trúc' },
      { icon: 'pi pi-book',             label: 'Sách',      name: 'book sách tài liệu' },
      { icon: 'pi pi-database',         label: 'Dữ liệu',   name: 'database dữ liệu' },
      { icon: 'pi pi-server',           label: 'Server',    name: 'server máy chủ' },
      { icon: 'pi pi-lightbulb',        label: 'Ý tưởng',   name: 'lightbulb ý tưởng sáng tạo' },
      { icon: 'pi pi-objects-column',   label: 'Module',    name: 'objects column module layout' },
      { icon: 'pi pi-chart-bar',        label: 'Cột',       name: 'chart bar cột thống kê' },
      { icon: 'pi pi-chart-pie',        label: 'Tròn',      name: 'chart pie biểu đồ tròn' },
      { icon: 'pi pi-chart-scatter',    label: 'Điểm',      name: 'chart scatter biểu đồ điểm' },
      { icon: 'pi pi-map',              label: 'Bản đồ',    name: 'map bản đồ roadmap' },
      { icon: 'pi pi-map-marker',       label: 'Vị trí',    name: 'map marker vị trí địa điểm' },
    ],
  },
  {
    label: 'Status / State',
    contexts: ['priority', 'sprint', 'project', 'state'],
    icons: [
      { icon: 'pi pi-check-circle',    label: 'Xong',       name: 'check circle hoàn thành xong' },
      { icon: 'pi pi-check-square',    label: 'Tick ô',     name: 'check square checkbox hoàn thành' },
      { icon: 'pi pi-clock',           label: 'Đồng hồ',    name: 'clock đồng hồ thời gian' },
      { icon: 'pi pi-hourglass',       label: 'Cát',        name: 'hourglass cát chờ đợi' },
      { icon: 'pi pi-pause-circle',    label: 'Tạm dừng',   name: 'pause circle tạm dừng' },
      { icon: 'pi pi-play',            label: 'Phát',       name: 'play phát bắt đầu' },
      { icon: 'pi pi-play-circle',     label: 'Chạy',       name: 'play circle chạy bắt đầu' },
      { icon: 'pi pi-stop-circle',     label: 'Dừng',       name: 'stop circle dừng' },
      { icon: 'pi pi-spin pi-spinner', label: 'Đang chạy',  name: 'spinner loading đang chạy' },
      { icon: 'pi pi-verified',        label: 'Xác thực',   name: 'verified xác thực approved' },
    ],
  },
  {
    label: 'Arrow / Direction',
    contexts: ['priority'],
    icons: [
      { icon: 'pi pi-arrow-up',          label: 'Lên',      name: 'arrow up mũi tên lên cao' },
      { icon: 'pi pi-arrow-down',        label: 'Xuống',    name: 'arrow down mũi tên xuống thấp' },
      { icon: 'pi pi-arrow-right',       label: 'Phải',     name: 'arrow right mũi tên phải' },
      { icon: 'pi pi-arrow-left',        label: 'Trái',     name: 'arrow left mũi tên trái' },
      { icon: 'pi pi-arrow-up-right',    label: 'Tăng',     name: 'arrow up right tăng tốt' },
      { icon: 'pi pi-arrow-down-right',  label: 'Giảm',     name: 'arrow down right giảm' },
      { icon: 'pi pi-angle-double-up',   label: 'Rất cao',  name: 'angle double up khẩn cấp rất cao' },
      { icon: 'pi pi-angle-double-down', label: 'Rất thấp', name: 'angle double down rất thấp' },
      { icon: 'pi pi-sort-alt',          label: 'Sắp xếp',  name: 'sort alt sắp xếp hai chiều' },
    ],
  },
  {
    label: 'People / Team',
    icons: [
      { icon: 'pi pi-user',         label: 'Người dùng', name: 'user người dùng thành viên' },
      { icon: 'pi pi-user-plus',    label: 'Thêm người', name: 'user plus thêm thành viên mới' },
      { icon: 'pi pi-user-minus',   label: 'Xóa người',  name: 'user minus xóa thành viên' },
      { icon: 'pi pi-user-edit',    label: 'Sửa người',  name: 'user edit sửa thành viên' },
      { icon: 'pi pi-users',        label: 'Nhóm',       name: 'users nhóm team đội' },
      { icon: 'pi pi-id-card',      label: 'Thẻ ID',     name: 'id card thẻ nhận diện' },
      { icon: 'pi pi-address-book', label: 'Danh bạ',    name: 'address book danh bạ liên hệ' },
      { icon: 'pi pi-at',           label: 'Mention',    name: 'at mention liên hệ email' },
      { icon: 'pi pi-comments',     label: 'Nhận xét',   name: 'comments nhận xét thảo luận' },
      { icon: 'pi pi-comment',      label: 'Bình luận',  name: 'comment bình luận phản hồi' },
      { icon: 'pi pi-inbox',        label: 'Hộp thư',    name: 'inbox hộp thư đến' },
      { icon: 'pi pi-envelope',     label: 'Email',      name: 'envelope thư email gửi' },
    ],
  },
  {
    // pi-wrench chuyển sang Bug/Issue
    label: 'Dev / Code',
    contexts: ['project'],
    icons: [
      { icon: 'pi pi-code',           label: 'Code',     name: 'code lập trình dev' },
      { icon: 'pi pi-file-code',      label: 'File code', name: 'file code tập tin mã nguồn' },
      { icon: 'pi pi-github',         label: 'GitHub',   name: 'github git repository kho lưu' },
      { icon: 'pi pi-gitlab',         label: 'GitLab',   name: 'gitlab git repository' },
      { icon: 'pi pi-slack',          label: 'Slack',    name: 'slack chat nhóm' },
      { icon: 'pi pi-discord',        label: 'Discord',  name: 'discord chat cộng đồng' },
      { icon: 'pi pi-android',        label: 'Android',  name: 'android mobile app di động' },
      { icon: 'pi pi-apple',          label: 'Apple',    name: 'apple ios mac' },
      { icon: 'pi pi-google',         label: 'Google',   name: 'google cloud workspace' },
      { icon: 'pi pi-microsoft',      label: 'Microsoft', name: 'microsoft windows azure' },
      { icon: 'pi pi-cloud',          label: 'Cloud',    name: 'cloud điện toán đám mây' },
      { icon: 'pi pi-cloud-upload',   label: 'Upload',   name: 'cloud upload tải lên' },
      { icon: 'pi pi-cloud-download', label: 'Download', name: 'cloud download tải xuống' },
      { icon: 'pi pi-cog',            label: 'Cài đặt',  name: 'cog settings cài đặt' },
    ],
  },
  {
    label: 'File / Doc',
    icons: [
      { icon: 'pi pi-file',       label: 'File',     name: 'file tập tin tài liệu' },
      { icon: 'pi pi-file-pdf',   label: 'PDF',      name: 'file pdf tài liệu' },
      { icon: 'pi pi-file-word',  label: 'Word',     name: 'file word tài liệu văn bản' },
      { icon: 'pi pi-file-excel', label: 'Excel',    name: 'file excel bảng tính' },
      { icon: 'pi pi-file-edit',  label: 'Sửa file', name: 'file edit sửa tập tin' },
      { icon: 'pi pi-copy',       label: 'Sao chép', name: 'copy sao chép clone' },
      { icon: 'pi pi-upload',     label: 'Upload',   name: 'upload tải lên' },
      { icon: 'pi pi-download',   label: 'Download', name: 'download tải xuống' },
      { icon: 'pi pi-print',      label: 'In',       name: 'print in ấn' },
      { icon: 'pi pi-share-alt',  label: 'Chia sẻ',  name: 'share alt chia sẻ' },
      { icon: 'pi pi-link',       label: 'Liên kết', name: 'link liên kết url' },
      { icon: 'pi pi-paperclip',  label: 'Kẹp',      name: 'paperclip kẹp giấy đính kèm' },
    ],
  },
  {
    // pi-info-circle chuyển sang Bug/Issue
    label: 'General',
    icons: [
      { icon: 'pi pi-circle',          label: 'Tròn',       name: 'circle vòng tròn' },
      { icon: 'pi pi-circle-fill',     label: 'Tròn đậm',   name: 'circle fill vòng tròn đậm' },
      { icon: 'pi pi-square',          label: 'Vuông',      name: 'square hình vuông' },
      { icon: 'pi pi-minus',           label: 'Ngang',      name: 'minus gạch ngang trung bình' },
      { icon: 'pi pi-plus',            label: 'Thêm',       name: 'plus thêm mới tạo' },
      { icon: 'pi pi-times',           label: 'Xóa',        name: 'times xóa đóng' },
      { icon: 'pi pi-ellipsis-h',      label: 'Ba chấm',    name: 'ellipsis horizontal ba chấm' },
      { icon: 'pi pi-ellipsis-v',      label: 'Ba chấm dọc', name: 'ellipsis vertical ba chấm dọc' },
      { icon: 'pi pi-tag',             label: 'Nhãn',       name: 'tag nhãn' },
      { icon: 'pi pi-tags',            label: 'Nhiều nhãn', name: 'tags nhãn nhiều' },
      { icon: 'pi pi-question-circle', label: 'Câu hỏi',    name: 'question circle câu hỏi trợ giúp' },
      { icon: 'pi pi-search',          label: 'Tìm kiếm',   name: 'search tìm kiếm' },
      { icon: 'pi pi-filter',          label: 'Lọc',        name: 'filter lọc bộ lọc' },
      { icon: 'pi pi-sort',            label: 'Sắp xếp',    name: 'sort sắp xếp' },
      { icon: 'pi pi-home',            label: 'Trang chủ',  name: 'home trang chủ' },
      { icon: 'pi pi-th-large',        label: 'Lưới',       name: 'th large lưới grid' },
      { icon: 'pi pi-bars',            label: 'Danh sách',  name: 'bars danh sách menu' },
    ],
  },
];

export interface EmojiItem { emoji: string; label: string; name: string }
export interface EmojiGroup {
  label: string;
  icons: EmojiItem[];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    // 🔥 🔧 🧪 chuyển sang nhóm gốc (Cảm xúc / Lập trình)
    label: 'Bug & Lỗi',
    icons: [
      { emoji: '🐛', label: 'Bọ',        name: 'bo bug loi sự cố' },
      { emoji: '🐞', label: 'Bọ rùa',    name: 'bo rua ladybug beetle bug' },
      { emoji: '🚨', label: 'Cảnh báo',  name: 'canh bao siren alert warning critical' },
      { emoji: '⚠️', label: 'Nguy hiểm', name: 'nguy hiem warning danger loi nghiem trong' },
      { emoji: '💥', label: 'Crash',     name: 'crash explosion boom critical loi nặng' },
      { emoji: '🩹', label: 'Vá lỗi',    name: 'va loi patch hotfix fix bandage' },
      { emoji: '🎫', label: 'Ticket',    name: 'ticket issue bug task phieu' },
      { emoji: '🔴', label: 'Đỏ',        name: 'do red critical loi nghiem trong' },
      { emoji: '❌', label: 'Lỗi',       name: 'loi error fail x mark' },
      { emoji: '🤯', label: 'Sốc',       name: 'soc mind blown unexpected crash' },
      { emoji: '🆘', label: 'SOS',       name: 'sos help error nguy hiem' },
      { emoji: '🛑', label: 'Dừng',      name: 'dung stop block regression blocker' },
      { emoji: '⛔', label: 'Cấm',       name: 'cam no entry block forbidden' },
    ]
  },
  {
    label: 'Công việc & Công nghệ',
    icons: [
      { emoji: '🚀', label: 'Tên lửa',     name: 'ten lua rocket start khoi nghiep' },
      { emoji: '💻', label: 'Máy tính',     name: 'may tinh laptop computer code cong nghe' },
      { emoji: '🎨', label: 'Bảng màu',     name: 'thiet ke art design mau ve' },
      { emoji: '📝', label: 'Ghi chép',     name: 'ghi chep document note viet lach' },
      { emoji: '📊', label: 'Biểu đồ',      name: 'bieu do chart data phan tich' },
      { emoji: '⚙️', label: 'Bánh răng',    name: 'banh rang gear setting cau hinh' },
      { emoji: '🛠️', label: 'Công cụ',      name: 'cong cu tools sua chua' },
      { emoji: '🎯', label: 'Mục tiêu',     name: 'muc tieu target goal kpi' },
      { emoji: '💡', label: 'Ý tưởng',      name: 'y tuong lightbulb sang tao' },
      { emoji: '💼', label: 'Cặp da',       name: 'cap da briefcase cong viec ho so' },
      { emoji: '🖥️', label: 'Màn hình',     name: 'man hinh screen monitor' },
      { emoji: '📈', label: 'Tăng trưởng',  name: 'tang truong growth trend tang' },
      { emoji: '📉', label: 'Giảm sút',     name: 'giam sut decrease trend giam' },
      { emoji: '📎', label: 'Kẹp giấy',     name: 'kep giay clip' },
      { emoji: '✉️', label: 'Thư',          name: 'thu email letter mail' },
      { emoji: '✏️', label: 'Bút chì',      name: 'but chi pencil draft nhap' },
      { emoji: '🖊️', label: 'Bút mực',      name: 'but muc pen viet' },
      { emoji: '🔍', label: 'Kính lúp',     name: 'kinh lup magnify tim kiem' },
      { emoji: '📋', label: 'Clipboard',    name: 'clipboard ban ke hoach copy' },
      { emoji: '🗂️', label: 'Hồ sơ',       name: 'ho so file folder quan ly' },
      { emoji: '📁', label: 'Thư mục',      name: 'thu muc folder' },
      { emoji: '📂', label: 'Thư mục mở',  name: 'thu muc mo open folder' },
      { emoji: '🗃️', label: 'Lưu trữ',     name: 'luu tru archive storage' },
    ]
  },
  {
    label: 'Lập trình & Tech',
    icons: [
      { emoji: '👨‍💻', label: 'Lập trình viên', name: 'lap trinh vien developer coder' },
      { emoji: '🤖', label: 'Robot AI',         name: 'robot ai tu dong hoa automation' },
      { emoji: '⌨️', label: 'Bàn phím',         name: 'ban phim keyboard typing' },
      { emoji: '🖱️', label: 'Chuột',            name: 'chuot mouse' },
      { emoji: '🔌', label: 'Cắm điện',         name: 'cam dien plugin connect ket noi' },
      { emoji: '💾', label: 'Đĩa mềm',          name: 'dia mem floppy save luu' },
      { emoji: '💿', label: 'Đĩa CD',           name: 'dia cd dvd deploy' },
      { emoji: '📡', label: 'Ăng ten',          name: 'ang ten antenna api signal' },
      { emoji: '🌐', label: 'Web',              name: 'web internet globe network' },
      { emoji: '🔗', label: 'Liên kết',         name: 'lien ket link url endpoint' },
      { emoji: '🧱', label: 'Khối xây',         name: 'khoi xay block build component' },
      { emoji: '⚡', label: 'Tốc độ',           name: 'toc do lightning fast performance' },
      { emoji: '🔧', label: 'Cờ lê',            name: 'co le wrench fix debug' },
      { emoji: '🧪', label: 'Test',             name: 'test thu nghiem chemistry lab' },
      { emoji: '🔬', label: 'Kính hiển vi',     name: 'kinh hien vi microscope analyze' },
      { emoji: '📱', label: 'Điện thoại',       name: 'dien thoai mobile phone app' },
    ]
  },
  {
    // 🤝 chuyển sang Nhóm & Giao tiếp
    label: 'Cảm xúc & Tương tác',
    icons: [
      { emoji: '😄', label: 'Cười tươi',    name: 'cuoi tuoi smile happy vui ve' },
      { emoji: '😁', label: 'Cười rạng',    name: 'cuoi rang rang beam grin' },
      { emoji: '😉', label: 'Nháy mắt',     name: 'nhay mat wink' },
      { emoji: '😍', label: 'Thích thú',    name: 'yeu thich love heart eyes thich thu' },
      { emoji: '🥳', label: 'Vui mừng',     name: 'vui mung celebrate party tiec tùng' },
      { emoji: '😎', label: 'Ngầu',         name: 'ngau cool glasses kinh' },
      { emoji: '🤔', label: 'Suy nghĩ',     name: 'suy nghi think ngam nghi' },
      { emoji: '😤', label: 'Quyết tâm',    name: 'quyet tam determined strong' },
      { emoji: '🧐', label: 'Phân tích',    name: 'phan tich analyze inspect' },
      { emoji: '😌', label: 'Hài lòng',     name: 'hai long satisfied pleased' },
      { emoji: '🥰', label: 'Yêu quý',      name: 'yeu quy adorable love fond' },
      { emoji: '🤩', label: 'Ngưỡng mộ',    name: 'nguong mo star struck amazed' },
      { emoji: '🔥', label: 'Nhiệt huyết',  name: 'nhiet huyet fire hot chay' },
      { emoji: '✨', label: 'Lấp lánh',     name: 'lap lanh sparkles xinh dep' },
      { emoji: '⭐', label: 'Ngôi sao',     name: 'ngoi sao star uu tu' },
      { emoji: '💫', label: 'Tỏa sáng',     name: 'toa sang dizzy star sáng' },
      { emoji: '👍', label: 'Đồng ý',       name: 'dong y like thumbs up tot' },
      { emoji: '👎', label: 'Không đồng ý', name: 'khong dong y dislike thumbs down' },
      { emoji: '🎉', label: 'Chúc mừng',    name: 'chuc mung party celebrate tiec' },
      { emoji: '👏', label: 'Vỗ tay',       name: 'vo tay clap hoan ho' },
      { emoji: '❤️', label: 'Trái tim',     name: 'trai tim heart yeu' },
      { emoji: '💙', label: 'Tim xanh',     name: 'tim xanh blue heart' },
      { emoji: '💚', label: 'Tim xanh lá',  name: 'tim xanh la green heart' },
      { emoji: '🧡', label: 'Tim cam',      name: 'tim cam orange heart' },
      { emoji: '💪', label: 'Cố lên',       name: 'co len strong power nang luc' },
      { emoji: '🙌', label: 'Hai tay',      name: 'hai tay raising hands cheer' },
      { emoji: '👊', label: 'Đấm',          name: 'dam fist bump dong doi team' },
      { emoji: '🤜🤛', label: 'Đồng đội',  name: 'dong doi team fist bump' },
      { emoji: '💯', label: 'Điểm 10',      name: 'diem 10 tram diem perfect tot' },
    ]
  },
  {
    // 📍 chuyển sang Đồ vật & Ký hiệu
    label: 'Thành tích & Mục tiêu',
    icons: [
      { emoji: '🏆', label: 'Cúp vàng',          name: 'cup vang trophy gold cup' },
      { emoji: '🥇', label: 'Huy chương vàng',    name: 'huy chuong vang medal gold nhat' },
      { emoji: '🥈', label: 'Huy chương bạc',     name: 'huy chuong bac medal silver nhi' },
      { emoji: '🥉', label: 'Huy chương đồng',    name: 'huy chuong dong medal bronze ba' },
      { emoji: '🎖️', label: 'Huân chương',        name: 'huan chuong military medal khen thuong' },
      { emoji: '🎗️', label: 'Ruy băng',           name: 'ruy bang ribbon nhan thuc' },
      { emoji: '🏅', label: 'Huy hiệu',           name: 'huy hieu sports medal' },
      { emoji: '🎀', label: 'Nơ ruy băng',        name: 'no ruy bang bow ribbon' },
      { emoji: '🏁', label: 'Đích đến',           name: 'dich den flag finish hoan thanh' },
      { emoji: '🚩', label: 'Cờ đỏ',              name: 'co do red flag moc milestone' },
      { emoji: '🎌', label: 'Hai cờ',             name: 'hai co two flags ceremony' },
      { emoji: '✅', label: 'Hoàn thành',          name: 'hoan thanh check mark done complete' },
      { emoji: '☑️', label: 'Tick',               name: 'tick check checkbox done' },
      { emoji: '🆕', label: 'Mới',                name: 'moi new feature' },
      { emoji: '🔝', label: 'Top',                name: 'top up cao nhat' },
      { emoji: '💎', label: 'Kim cương',          name: 'kim cuong diamond quy gia premium' },
      { emoji: '👑', label: 'Vương miện',         name: 'vuong mien crown king top nhat' },
    ]
  },
  {
    label: 'Đồ vật & Ký hiệu',
    icons: [
      { emoji: '🔑', label: 'Chìa khóa',     name: 'chia khoa key mat khau' },
      { emoji: '🗝️', label: 'Chìa cổ',       name: 'chia co old key vintage' },
      { emoji: '🔒', label: 'Khóa',          name: 'khoa lock bao mat' },
      { emoji: '🔓', label: 'Mở khóa',       name: 'mo khoa unlock access' },
      { emoji: '🔔', label: 'Thông báo',     name: 'thong bao bell notification' },
      { emoji: '🔕', label: 'Tắt thông báo', name: 'tat thong bao mute bell' },
      { emoji: '📦', label: 'Hộp hàng',      name: 'hop hang box package module' },
      { emoji: '📅', label: 'Lịch trình',     name: 'lich trinh calendar schedule' },
      { emoji: '📆', label: 'Lịch tháng',     name: 'lich thang month calendar' },
      { emoji: '🏷️', label: 'Thẻ tag',       name: 'the tag label phan loai' },
      { emoji: '📌', label: 'Ghim',          name: 'ghim pin chu y' },
      { emoji: '📍', label: 'Ghim đỏ',       name: 'ghim do red pin location milestone' },
      { emoji: '📢', label: 'Loa phát',       name: 'loa phat megaphone tuyen truyen' },
      { emoji: '📣', label: 'Loa cầm',       name: 'loa cam megaphone thong bao' },
      { emoji: '🔋', label: 'Pin đầy',       name: 'pin day battery nang luong' },
      { emoji: '🪫', label: 'Pin yếu',       name: 'pin yeu low battery' },
      { emoji: '⏰', label: 'Báo thức',       name: 'bao thuc alarm clock thoi gian' },
      { emoji: '⏱️', label: 'Bấm giờ',       name: 'bam gio stopwatch timer' },
      { emoji: '⏳', label: 'Cát đang chảy', name: 'cat dang chay hourglass pending' },
      { emoji: '⌛', label: 'Hết thời gian', name: 'het thoi gian hourglass done' },
      { emoji: '🛡️', label: 'Khiên bảo vệ', name: 'khien bao ve shield protect an toan' },
      { emoji: '🎁', label: 'Hộp quà',       name: 'hop qua gift present phan thuong' },
      { emoji: '🧲', label: 'Nam châm',       name: 'nam cham magnet thu hut' },
      { emoji: '🔭', label: 'Kính thiên văn', name: 'kinh thien van telescope vision tầm nhin' },
    ]
  },
  {
    label: 'Nhóm & Giao tiếp',
    icons: [
      { emoji: '👤', label: 'Người dùng',    name: 'nguoi dung user member thanh vien' },
      { emoji: '👥', label: 'Nhóm người',    name: 'nhom nguoi group team doi' },
      { emoji: '🧑‍🤝‍🧑', label: 'Đôi bạn', name: 'doi ban pair buddy pair programming' },
      { emoji: '👨‍👩‍👧‍👦', label: 'Gia đình', name: 'gia dinh family team' },
      { emoji: '🗣️', label: 'Diễn thuyết',  name: 'dien thuyet speaking presentation' },
      { emoji: '💬', label: 'Chat',          name: 'chat message nhan tin thao luan' },
      { emoji: '💭', label: 'Nghĩ',          name: 'nghi thought idea suy nghi' },
      { emoji: '📞', label: 'Gọi điện',      name: 'goi dien call phone' },
      { emoji: '📲', label: 'Di động',       name: 'di dong mobile call' },
      { emoji: '📧', label: 'Email',         name: 'email thu tu lien lac' },
      { emoji: '📨', label: 'Nhận thư',      name: 'nhan thu inbox email receive' },
      { emoji: '📩', label: 'Gửi thư',       name: 'gui thu send email' },
      { emoji: '📬', label: 'Hộp thư',       name: 'hop thu mailbox inbox' },
      { emoji: '🤝', label: 'Hợp tác',       name: 'hop tac handshake collaboration' },
      { emoji: '🧑‍💼', label: 'Chuyên gia', name: 'chuyen gia expert professional manager' },
      { emoji: '🧑‍🏫', label: 'Mentor',      name: 'mentor teacher lead giao vien' },
    ]
  },
  {
    // ⚡ chuyển sang Lập trình & Tech
    label: 'Thiên nhiên & Khác',
    icons: [
      { emoji: '🌍', label: 'Trái đất',        name: 'trai dat globe world toan cau' },
      { emoji: '🌎', label: 'Châu Mỹ',         name: 'chau my americas western' },
      { emoji: '🌏', label: 'Châu Á',          name: 'chau a asia pacific eastern' },
      { emoji: '🏠', label: 'Nhà',             name: 'nha home house trang chu' },
      { emoji: '🏢', label: 'Công ty',         name: 'cong ty building van phong' },
      { emoji: '🏗️', label: 'Xây dựng',       name: 'xay dung construction building' },
      { emoji: '🌲', label: 'Cây thông',       name: 'cay thong tree thien nhien' },
      { emoji: '🌱', label: 'Mầm cây',         name: 'mam cay sprout grow phat trien' },
      { emoji: '🍀', label: 'Cỏ 4 lá',        name: 'co 4 la clover may man' },
      { emoji: '🌸', label: 'Hoa anh đào',     name: 'hoa anh dao cherry blossom dep' },
      { emoji: '🌻', label: 'Hoa hướng dương', name: 'hoa huong duong sunflower happy' },
      { emoji: '☀️', label: 'Mặt trời',        name: 'mat troi sun anh sang' },
      { emoji: '🌙', label: 'Trăng',           name: 'trang moon night ban dem' },
      { emoji: '🌊', label: 'Sóng biển',       name: 'song bien wave ocean' },
      { emoji: '🌈', label: 'Cầu vồng',        name: 'cau vong rainbow hy vong' },
      { emoji: '❄️', label: 'Tuyết',           name: 'tuyet snow cold winter' },
      { emoji: '🔮', label: 'Tiên tri',        name: 'tien tri crystal ball forecast vision' },
      { emoji: '🧩', label: 'Mảnh ghép',       name: 'manh ghep puzzle lap rap integrate' },
      { emoji: '♻️', label: 'Tái chế',         name: 'tai che recycle sustainable' },
      { emoji: '✈️', label: 'Máy bay',         name: 'may bay plane travel du lich' },
      { emoji: '🚂', label: 'Tàu hỏa',         name: 'tau hoa train agile sprint' },
      { emoji: '🗺️', label: 'Bản đồ',         name: 'ban do map roadmap ke hoach' },
    ]
  }
];
